### ISSUE TITLE
Getting error while trying to run test

### ISSUE THREAD

**Issue by ishrafislam** [zerostep-ai/zerostep#17]
Getting below error:

```
Error: page.evaluate: Execution context was destroyed, most likely because of a navigation

  15 |   const aiArgs = {page, test}
  16 |
> 17 |   await ai("Press the login button", aiArgs)
     |           ^
  18 | });
  19 |

    at getViewportMetadata (D:\playwright-ai\node_modules\@zerostep\playwright\src\playwright.ts:124:31)
    at Object.getSnapshot (D:\playwright-ai\node_modules\@zerostep\playwright\src\playwright.ts:139:46)
    at sendTaskStartMessage (D:\playwright-ai\node_modules\@zerostep\playwright\src\index.ts:89:37)
    at D:\playwright-ai\node_modules\@zerostep\playwright\src\index.ts:45:13
    at D:\playwright-ai\node_modules\@zerostep\playwright\src\index.ts:34:10
    at ai (D:\playwright-ai\node_modules\@zerostep\playwright\src\index.ts:31:10)
    at D:\playwright-ai\tests\example.spec.ts:17:11
```

Here is my code:

```
import { test, expect } from '@playwright/test';
import { ai } from "@zerostep/playwright"

test('can navigate', async ({ browser }) => {
  const context = await browser.newContext({
    httpCredentials: {
      username: "username",
      password: "password"
    }
  });

  const page = await context.newPage();
  await page.goto('https://mywebsiteurl/');

  const aiArgs = {page, test}

  await ai("Press the login button", aiArgs)
});
```

![image](https://github.com/zerostep-ai/zerostep/assets/7996116/70d960a8-37ba-449d-9301-30598817d503)

**Comment by ishrafislam** [comment]
My website loaded a bit slow that's why this error occurred. Fixed it with waitUntill property in page.goto() function.

**Comment by khsheehan** [comment]
@tmcneal the Errors are thrown from the playwright calls. In this case it's worth investigating whether or not we're executing ai() steps when we shouldn't be, but I'd be cautious about adding our own waits.

**Comment by tmcneal** [comment]
Got it - I was thinking that it was a CDP call and CDP doesn't have some of the auto-wait stuff that Playwright includes. i.e. A similar issue to what we saw when switching from the CDP click to a Playwright click which eliminated some of the need for adding dynamic waits.

**Comment by ishrafislam** [comment]
As per my understanding when we use `page.goto()` it opens the browser page and hits the URL, but here code after this function call needs to be halted till the DOM is loaded. Also if `ai()` utilizes the waiting in it then it will be much more reliable for any type of wait in `page.goto()`.

Thanks for the response.
