### ISSUE TITLE
An unknown error occurred after running setup and example steps

### ISSUE THREAD

**Issue by sjloh9918** [zerostep-ai/zerostep#33]
Following the three setup steps listed on the readme and tried executing the example code shown under step 3 but I am getting 'an unknown error occurred' with no logs or ways to diagnose what the issue might be. I tried following the steps listed under the provided examples as well and am getting the same error of 'an unknown error occurred'. Does anyone know what the problem might be?

**Comment by tmcneal** [comment]
Hey @sjloh9918 - can you provide steps to reproduce? Also can you verify that you have a stable internet connection?

**Comment by sjloh9918** [comment]
@tmcneal I have stable internet connection. 

For steps, I just followed what was documented here: https://github.com/zerostep-ai/zerostep under the 'Setup' section and also the 'Examples' section.

**Comment by tmcneal** [comment]
I verified that those tests are working for me. Sorry but without more details on how to repro I am unable to help here. When this has come up before, the most common cause has been some sort of network connectivity issue, so that's my best guess on what's going on here.
