### ISSUE TITLE
How to use it for WebDriverIO

### ISSUE THREAD

**Issue by ShyamLSQ** [zerostep-ai/zerostep#34]
Can this AI be used for the Webdriver IO? If yes, can we get a template of the integration of this AI?

**Comment by tmcneal** [comment]
Hi @ShyamLSQ, ZeroStep is only supported for Playwright running on a JavaScript runtime (e.g. NodeJS). Support for other testing libraries (Selenium / WebDriver, Cypress, etc) is not supported.
