### ISSUE TITLE
Issue with Consistency: Suggestion

### ISSUE THREAD

**Issue by 11PRiyansh** [zerostep-ai/zerostep#36]
Similar prompt starts working differently, or randomly. Please suggest.
![Screenshot 2024-02-15 013437](https://github.com/zerostep-ai/zerostep/assets/160034930/907406c7-05c7-4280-9a7e-ec7c77b9ef4b)

**Comment by tmcneal** [comment]
I'd suggest replacing each of these with something like:

> Get all values from the Label column

> Get the label associated with the row that has a name value of 'severity'

> Get all values from the Label column
