### ISSUE TITLE
question about action after submit a form

### ISSUE THREAD

**Issue by andryi777** [zerostep-ai/zerostep#39]
Hi, 

I am starting using ZeroStep in my project but I notice that when I use the sentence (only with Playwright): 
`await page.getByPlaceholder('Search patient').click();`
 it takes a moment until the page is loaded to after that click in the "Search patient"; but when I use ZeroStep, I put the sentence 
`await ai(`Click on the "Search patient"`);`
The script fails because immediately tries to click on the object before the page is loaded, and the error says: 
`Error: elementHandle.click: Element is not attached to the DOM`

Do you know how can I fix it? Exist a way to apply the click action when the selector is becoming visible/stable/editable?

Here I share part of the code that I am using for only Playwright
```
    await page.goto('https://demo-company.com/');
    await page.getByPlaceholder('Enter your email').fill('testuser@company.com');
    await page.getByPlaceholder('Enter your Password').fill('admin123');
    await page.getByRole('button', { name: 'Sign in' }).click();
    await page.getByPlaceholder('Search patient').click();
    await page.getByPlaceholder('Search patient').fill('patient_test_Name');
```

And here, how I am using Playwright with ZeroStep
```
  await page.goto('https://demo-company.com/');
  await ai(`Enter the email ${email}`);
  await ai(`Enter the password ${password}`);
  await ai(`Click the Submit button`);
  await ai(`Click on the "Search patient"`);
  await ai(`Enter the Search patient as patient_test_Name`);
```

**Comment by dimitriharding** [comment]
Maybe stating/using a wait for visible should fix your issue:

```js
// ....
await ai(`Wait for "Search patient" to be visible`)
await ai(`Click on the "Search patient"`);
```

Something like that...

By default ```await page.getByPlaceholder('Search patient').click();``` will wait.

**Comment by andryi777** [comment]
Hi @dimitriharding thanks for your suggestion but after I applied it, the behavior ignores to wait a moment until the element can be interactable

![image](https://github.com/zerostep-ai/zerostep/assets/21963698/b6f385ef-7f2a-4033-abb4-5cb408ac3bcc)

Even if I change to other combinations, the behavior is the same:
```
await ai(`Wait for "Search patient" to be visible, enabled and stable`)
await ai(`Wait for "Search patient" to be attached`)
```

Could be something about configuration on ZeroStep?

**Comment by tmcneal** [comment]
ZeroStep AI steps will not auto-retry like regular Playwright steps. You could write this auto-retry logic in your own wrapper if you want, but what I would recommend is use an explicit "waitFor" command like `page.waitForURL` or `page.waitForSelector`. You can see some usages of these in the examples that we provide.
