### ISSUE TITLE
Need help how to pass ZEROSTEP_TOKEN in test 

### ISSUE THREAD

**Issue by soumya198821** [zerostep-ai/zerostep#6]
Currently while executing test , it is asking for token. Can you show it how you have passed the ZEROSTEP_TOKEN  in your example test .

**Comment by tmcneal** [comment]
Hi @soumya198821, please take a look at the [Setup section](https://github.com/zerostep-ai/zerostep#setup) in our README which describes how to pass the ZEROSTEP_TOKEN:

> This package relies on an environment variable with your zerostep token being exposed to the playwright process. This token can be found in your account on https://app.zerostep.com/. Do this however you'd like, e.g.
> export ZEROSTEP_TOKEN="<your token here>"

Basically what you'll need to do is:
- Go to https://app.zerostep.com and sign up so you get an API key
- Copy the API key and put it in an environment variable called `ZEROSTEP_TOKEN`. You'd want to save this in a `.bashrc` / `.zshrc` or some other file, depending on what shell you're using
- When you run a Playwright test that uses ZeroStep, it will get the token from that environment variable.
